## Dataset ##
*A manager at the bank is disturbed with more and more customers leaving their credit card services. They would really appreciate if one could predict for them who is gonna get churned so they can proactively go to the customer to provide them better services and turn customers' decisions in the opposite direction*

- Source: Kaggle
- Link: https://www.kaggle.com/datasets/sakshigoyal7/credit-card-customers/data

## Problem Statement ##

A manager at the bank is disturbed with more and more customers leaving their credit card services. They would really appreciate if one could predict for them who is gonna get churned so they can proactively go to the customer to provide them better services and turn customers' decisions in the opposite direction

## Business Questions ##
- Do customers with more dependents churn more?
- Does gender affect churn rate?
- Does marital status or age affect the churn rate?
- Do platinum/gold card holders churn less than blue card holders?
- Is there a specific age group with a higher churn rate?
- Is there sign that the customer is going to cancel their account?
- What Income Category are most of the churners?
- Do education level have a role in being a churner or not.

Let's start by importing our libraries

In [161]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import plotly.express as px
import plotly.io as pio
pio.templates.default = "plotly_dark"

Loading the data...

In [162]:
bank_df = pd.read_csv('BankChurners.csv')
pd.set_option('display.max_columns', None) # to display all columns in the DataFrame
bank_df.sample(20)

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
286,720272958,Attrited Customer,48,M,2,High School,Married,$120K +,Blue,36,3,3,3,27126.0,0,27126.0,0.953,1000,25,0.786,0.000,0.996610,0.003388
5374,718921683,Existing Customer,49,M,4,Unknown,Married,$80K - $120K,Blue,38,6,6,3,9738.0,1835,7903.0,0.763,4816,49,0.885,0.188,0.000275,0.999720
1188,714350658,Existing Customer,32,M,1,Graduate,Single,Unknown,Blue,26,6,3,4,18889.0,1880,17009.0,0.702,2979,55,0.774,0.100,0.000484,0.999520
9645,713965683,Existing Customer,35,M,3,Post-Graduate,Married,$80K - $120K,Blue,28,3,1,2,4380.0,0,4380.0,0.719,17258,121,0.704,0.000,0.000067,0.999930
8722,715908558,Existing Customer,44,M,0,Graduate,Unknown,$60K - $80K,Silver,36,1,1,1,29572.0,1584,27988.0,0.738,7566,88,0.600,0.054,0.000026,0.999970
8195,790149483,Existing Customer,42,M,3,Uneducated,Single,$40K - $60K,Blue,35,2,3,3,8566.0,1484,7082.0,0.807,4195,89,0.854,0.173,0.000323,0.999680
1912,818923158,Existing Customer,55,M,2,Graduate,Married,$60K - $80K,Blue,50,5,2,4,2145.0,1207,938.0,0.521,1275,31,0.476,0.563,0.000327,0.999670
6228,715555833,Existing Customer,47,F,3,Unknown,Single,Less than $40K,Blue,34,6,3,0,4862.0,0,4862.0,0.695,4167,86,0.593,0.000,0.000076,0.999920
2216,715206408,Existing Customer,31,F,1,High School,Single,Less than $40K,Blue,22,5,1,5,6662.0,0,6662.0,0.934,3264,83,0.766,0.000,0.000250,0.999750
6943,715941633,Existing Customer,50,F,0,Graduate,Married,Less than $40K,Blue,36,3,3,3,1438.3,0,1438.3,0.718,3800,69,0.533,0.000,0.000260,0.999740
7263,708894183,Existing Customer,53,M,3,College,Single,$120K +,Silver,44,4,4,2,34516.0,1073,33443.0,0.558,4485,86,0.755,0.031,0.000198,0.999800
2193,711625683,Existing Customer,46,M,4,Doctorate,Married,$120K +,Blue,36,3,2,5,3104.0,862,2242.0,1.057,2781,74,0.682,0.278,0.000857,0.999140
3839,720950283,Attrited Customer,47,M,3,High School,Married,$80K - $120K,Blue,34,3,3,3,21359.0,0,21359.0,0.551,2064,63,0.853,0.000,0.996730,0.003265
8351,719192808,Existing Customer,51,M,4,Graduate,Single,$120K +,Blue,36,2,1,1,3168.0,2147,1021.0,0.663,4674,71,0.821,0.678,0.000035,0.999970
199,718030083,Existing Customer,59,M,1,College,Married,$60K - $80K,Blue,36,4,1,2,7871.0,1687,6184.0,1.242,1428,22,1.444,0.214,0.000050,0.999950
3881,712822758,Existing Customer,52,F,3,Uneducated,Married,Less than $40K,Blue,33,6,3,3,5677.0,1403,4274.0,0.951,2730,58,0.758,0.247,0.000323,0.999680
38,715190283,Existing Customer,57,F,1,Graduate,Unknown,$40K - $60K,Blue,49,3,3,2,3672.0,886,2786.0,1.320,1464,28,0.556,0.241,0.000169,0.999830
9070,708748833,Existing Customer,37,F,3,Graduate,Single,$40K - $60K,Blue,25,2,2,3,9875.0,1239,8636.0,0.939,8920,105,0.694,0.125,0.000199,0.999800
8866,788824083,Existing Customer,41,M,2,Uneducated,Single,$120K +,Blue,24,2,2,1,34516.0,1022,33494.0,0.743,8202,88,0.913,0.030,0.000071,0.999930
3705,712263258,Existing Customer,49,F,2,Uneducated,Married,Less than $40K,Blue,38,6,3,3,2468.0,0,2468.0,1.057,3371,62,0.676,0.000,0.000311,0.999690

No need for those last 2 columns, let's drop them.

But I'll chose the hard way and drop them by name not index cause it's more safe.

In [163]:
bank_df.drop(columns = ['Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2', 'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1'], inplace = True)
bank_df

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462
10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291,60,0.818,0.000
10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395,62,0.722,0.000
10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189

Let's find more info about our data..

In [164]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CLIENTNUM                 10127 non-null  int64
 1   Attrition_Flag            10127 non-null  object
 2   Customer_Age              10127 non-null  int64
 3   Gender                    10127 non-null  object
 4   Dependent_count           10127 non-null  int64
 5   Education_Level           10127 non-null  object
 6   Marital_Status            10127 non-null  object
 7   Income_Category           10127 non-null  object
 8   Card_Category             10127 non-null  object
 9   Months_on_book            10127 non-null  int64
 10  Total_Relationship_Count  10127 non-null  int64
 11  Months_Inactive_12_mon    10127 non-null  int64
 12  Contacts_Count_12_mon     10127 non-null  int64
 13  Credit_Limit              10127 non-null  float64
 14  Total_Revolving_Bal       10127 non-null  int64
 15  Avg_Open_To_Buy           10127 non-null  float64
 16  Total_Amt_Chng_Q4_Q1      10127 non-null  float64
 17  Total_Trans_Amt           10127 non-null  int64
 18  Total_Trans_Ct            10127 non-null  int64
 19  Total_Ct_Chng_Q4_Q1       10127 non-null  float64
 20  Avg_Utilization_Ratio     10127 non-null  float64
dtypes: float64(5), int64(10), object(6)
memory usage: 1.6+ MB

In [165]:
bank_df.isnull().sum()

CLIENTNUM                   0
Attrition_Flag              0
Customer_Age                0
Gender                      0
Dependent_count             0
Education_Level             0
Marital_Status              0
Income_Category             0
Card_Category               0
Months_on_book              0
Total_Relationship_Count    0
Months_Inactive_12_mon      0
Contacts_Count_12_mon       0
Credit_Limit                0
Total_Revolving_Bal         0
Avg_Open_To_Buy             0
Total_Amt_Chng_Q4_Q1        0
Total_Trans_Amt             0
Total_Trans_Ct              0
Total_Ct_Chng_Q4_Q1         0
Avg_Utilization_Ratio       0
dtype: int64

Seems like we got some clean data, no Nulls at all.. Saves me a lot of time.

Let's move on with finding out if there's any duplicates?

In [166]:
bank_df.duplicated().sum()

np.int64(0)

No duplicates as we can see, moving on..

Let's check how our data looks for one last time.

In [167]:
bank_df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000

Time to start our EDA.

## Target Variable Analysis: ##

In [170]:
fig = px.pie(bank_df, names = 'Attrition_Flag',
            title = 'Attrition Rate', color_discrete_sequence=px.colors.qualitative.D3)
fig.update_traces(textinfo='label + percent')
fig.show()

ValueError:
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

The bank is doing well by keeping those 83.9%, let's find out why those 16.1% have left the bank.

## Univariate & Bivariate Analysis ##

In [ ]:
fig = px.histogram(bank_df, x = 'Customer_Age', color = 'Attrition_Flag',
                    title = 'Distribution of Customer Age by Attrition Flag',
                    color_discrete_sequence = px.colors.qualitative.D3,
                    text_auto = '.1f', barnorm = 'percent', barmode = 'group',
                    nbins = 20)

fig.show()

The churn rate looks roughly consistent across ages. Moving on..

In [ ]:
fig = px.histogram(bank_df, x = 'Marital_Status', color = 'Attrition_Flag',
                    title = 'Distribution of Customer Marital Status by Attrition Flag',
                    color_discrete_sequence = px.colors.qualitative.D3,
                    text_auto = '.1f', barnorm = 'percent', barmode = 'group')
fig.show()

I see here it has no relation with the marital status.

In [ ]:
fig = px.histogram(bank_df, x = 'Income_Category', color = 'Attrition_Flag',
                    title = 'Distribution of Income Category by Attrition Flag',
                    barmode = 'group',
                    category_orders = {'Income_Category': ['Less than $40K', '$40K - $60K', '$60K - $80K', '$80K - $120K', '$120K +', 'Unknown']},
                    color_discrete_sequence = px.colors.qualitative.D3,
                    barnorm = 'percent', text_auto = '.1f')
fig.show()

The attrition rate for each category are almost the same, moving on..

In [ ]:
fig = px.histogram(bank_df, x = 'Avg_Utilization_Ratio', color = 'Attrition_Flag',
                    title = 'Average Utilization Ratio by Attrition Flag', barmode = 'group', text_auto = '.1f',
                    color_discrete_sequence = px.colors.qualitative.D3,
                    barnorm = 'percent', nbins = 20)
fig.show()

Most of the churned Customer hava a **0** utilization ratio which is intuitive, while **52.9%** of those who fully utilize their card are churners, this should be invistigated.

In [ ]:
fig = px.histogram(bank_df, x = 'Total_Trans_Amt', color = 'Attrition_Flag',
                    title = 'Total Transaction Amount by Attrition Flag',
                    barmode = 'group', text_auto = '.1f', nbins = 20, barnorm = 'percent',
                    color_discrete_sequence = px.colors.qualitative.D3)
fig.update_traces(marker_line_width=0.2, marker_line_color='black')
fig.show()

## Key Insight: Transaction Amount & Churn

The **$3,000** spending mark appears to be a critical threshold — customers who spend below this amount are significantly more likely to churn.

Notably, the **$6,000–$7,000** range shows a churn rate of ~68%, and the **$9,000–$11,000** range shows an unusually high churn concentration, reaching 100% at the upper end — suggesting these may be outlier segments worth investigating further.

In [ ]:
fig = px.histogram(bank_df, x = 'Card_Category', color = 'Attrition_Flag',
                    title = 'Distribution of Card Category by Attrition Flag',
                    color_discrete_sequence=px.colors.qualitative.D3,
                    barnorm = 'percent', text_auto = '.1f', barmode = 'group') #type:ignore
fig.show()

The Attrition Rate is a bit higher for the platinum Card, that could lead us to something!

In [ ]:
fig = px.pie(bank_df, names = 'Gender', title = 'Gender count', color_discrete_sequence=px.colors.qualitative.D3)
fig.update_traces(textinfo='label + percent')
fig.show()

We seem to have a relatively equal number of both genders.

In [ ]:
fig = px.histogram(bank_df, x='Total_Ct_Chng_Q4_Q1', color='Attrition_Flag',
                   title='Transaction Count Change (Q4 vs Q1) by Attrition Flag',
                   barmode='group', barnorm='percent', text_auto='.1f',
                   color_discrete_sequence=px.colors.qualitative.D3, nbins=20)
fig.update_traces(marker_line_width=0)
fig.show()

## Transaction Count Trend & Churn

Churned customers are heavily concentrated at **Q4/Q1 ratios below 1.0**, indicating a declining transaction frequency over time. Customers whose transaction count increased from Q1 to Q4 (ratio > 1.0) are significantly more likely to remain active, suggesting that an upward engagement trend is a strong retention signal.

In [ ]:
fig = px.imshow(bank_df.select_dtypes(include='number').corr(),
                title='Correlation Heatmap',
                color_continuous_scale='Tealgrn',
                text_auto='.2f')
fig.update_layout(width=1000, height=800)
fig.show()

*Findings of this HeatMap:*

Positive Corr:
1. Correlation between Months_On_Book and Customer_Age are 0.79 meaning that the older they get, the more they use their credit card.
2. Full correlation between Credit Limit and Avg_open_To_buy which means they're identical, one of them could be dropped.
3. Correlation between Total Transactions and Total Transactions Amount are 0.81 which is Intuitive.
4. Total_Revolving_Bal and Avg_Utilization_Ratio (0.62), higher balance means higher utilization, expected.

Negative Corr:
1. Credit_Limit and Avg_Utilization_Ratio (-0.48), customers with higher credit limits tend to use a smaller proportion of it.
2. Avg_Open_To_Buy and Avg_Utilization_Ratio (-0.54), same logic, more available credit = lower utilization

Notable Corr:
1. Total_Relationship_Count and Total_Trans_Amt (-0.35), customers with more products actually spend less per transaction, interesting.
2. Total_Relationship_Count and Total_Trans_Ct (-0.24), same pattern.

In [ ]:
fig = px.histogram(bank_df, x='Credit_Limit', color='Attrition_Flag',
                   title='Credit Limit distribution',
                   color_discrete_sequence=px.colors.qualitative.D3)
fig.update_traces(marker_line_width=0.2, marker_line_color='black')
fig.show()

the 35k Limit is weirdly much used, otherwise, we can see that after the 5k limit and below are the most common.

In [ ]:
fig = px.histogram(bank_df, x='Credit_Limit', color='Attrition_Flag',
                   title='Credit Limit distribution',
                   barmode='group',
                   color_discrete_sequence=px.colors.qualitative.D3,
                   barnorm='percent', text_auto='.1f', nbins=20)
fig.show()

- But the attrition rate for the 35k limit is almost the same as the other categories
- Also, the lowest creadit limit has the highest churn rate.

Let's see if it has something to do with their education level.

In [ ]:
fig = px.histogram(bank_df, x = 'Education_Level', color= 'Attrition_Flag',
                    title='Total Revolving Balance distribution by Attrition Flag',
             barmode='group', color_discrete_sequence=px.colors.qualitative.D3,
             nbins=10, text_auto='.1f', barnorm='percent')
fig.update_traces(marker_line_width=0)
fig.show()

Education level seems to have no relation, distribution is normal, but there's a slight increase in attrition rate for those who hold a Doctorate.

In [ ]:
fig = px.histogram(bank_df, x = 'Dependent_count', color= 'Attrition_Flag',
                    title='Total Revolving Balance distribution by Attrition Flag',
             barmode='group', color_discrete_sequence=px.colors.qualitative.D3,
             nbins=10, text_auto = '.1f', barnorm='percent')
fig.update_traces(marker_line_width=0)
fig.show()

Nothing to look at here.

In [ ]:
fig = px.histogram(bank_df, x ='Total_Revolving_Bal', color= 'Attrition_Flag',
                    title='Total Revolving Balance distribution by Attrition Flag',
             barmode='group', color_discrete_sequence=px.colors.qualitative.D3,
             nbins=10, text_auto='.1f', barnorm='percent')
fig.update_traces(marker_line_width=0)
fig.show()

The Attratition rate increases for balances that range from 0 to $500, and the $2500+ balances.

In [ ]:
fig = px.histogram(bank_df, x ='Total_Relationship_Count', color= 'Attrition_Flag',
                    title='Total Relationships distribution by Attrition Flag',
             barmode='group', color_discrete_sequence=px.colors.qualitative.D3,
             nbins=10, text_auto='.1f', barnorm='percent')
fig.update_traces(marker_line_width=0)
fig.show()

The less relationships the customer has with the bank, the more likely they are to churn.

In [ ]:
fig = px.histogram(bank_df, x ='Months_Inactive_12_mon', color= 'Attrition_Flag',
                    title='Total Relationships distribution by Attrition Flag',
             barmode='group', color_discrete_sequence=px.colors.qualitative.D3,
             nbins=10, text_auto='.1f', barnorm='percent')
fig.update_traces(marker_line_width=0)
fig.show()

While 0 Inactivity takes a good percentage of chruners, the inactivity period from 2 months and more are noticably increasing in churners, this should be invistigated.

In [ ]:
fig = px.histogram(bank_df, x ='Total_Trans_Ct', color= 'Attrition_Flag',
                    title='Total Transactions distribution by Attrition Flag'
                    , barmode='group', color_discrete_sequence=px.colors.qualitative.D3,
                    nbins=30, text_auto='.1f', barnorm='percent')
fig.update_traces(marker_line_width=0)
fig.show()

Seems like the less transaction people do, the more likely they are to cancel their card.

Let's ask a question, did they get the card that matches their income category?

In [ ]:
attrited = bank_df[bank_df['Attrition_Flag'] == 'Attrited Customer']

fig = px.histogram(attrited, x='Education_Level', color='Card_Category',
                    title='Education Level by Card Category (Attrited Customers)',
                    barmode='group',
                    color_discrete_sequence=px.colors.qualitative.D3,
                    text_auto='.1f', barnorm='percent')
fig.update_traces(marker_line_width=0)
fig.show()

The data is skewed towards the blue card but that's cause it's the most held card, but it seems to have no relation with the Education Level.

In [ ]:
fig = px.histogram(bank_df, x ='Months_on_book', color= 'Attrition_Flag',
                    title='Total Months on book distribution by Attrition Flag',
                    barmode='group', color_discrete_sequence=px.colors.qualitative.D3,
                    nbins=30, text_auto='.1f', barnorm='percent')
fig.show()

I guess it has nothing to do with how many months they been on the book.

---------------------------------------------------------------------------------------------------------------------------

*Proceeding with multivariate Analysis*

In [ ]:
fig = px.scatter(bank_df, x='Credit_Limit', y='Avg_Utilization_Ratio',
                 color='Attrition_Flag', title='Credit Limit vs Avg Utilization Ratio',
                 color_discrete_sequence=px.colors.qualitative.D3)
fig.show()

The less the Credit limit, the more the utilization ratio, confirmed by the -0.48 correlation on the previous heatmap.
High limit customers rarely churn.

A noticable amount of churned customers had 0 balance as shown by the yellow horizontal line where we rarely see any teal dots, that's an indicator that the 0 balance is an indicator that the customer is likely to churn.

**Customers with low credit limits and near-zero utilization are the highest churn risk — the bank should target this segment proactively with engagement offers or credit limit increases.

In [ ]:
fig = px.scatter(bank_df, x='Total_Trans_Amt', y='Total_Trans_Ct',
                 color='Attrition_Flag',
                 title='Transaction Amount vs Transaction Count by Attrition Flag',
                 color_discrete_sequence=px.colors.qualitative.D3)
fig.show()

- People who make less than **60** transactions and spend less that **3k** are the most likely to churn.
- We see here that the churners are foucused nearly before the **10k** Amount
- There are visibly two separate teal clouds — one in the 0-$10k range and another in the $10k-$18k range, suggesting two behavioral segments among existing customers: moderate users and heavy users Churned customers don't appear in the heavy user segment at all

In [ ]:
fig = px.scatter(bank_df, x='Total_Revolving_Bal', y='Total_Trans_Ct',
                 color='Attrition_Flag',
                 title='Transaction Count vs Revolving Balance by Attrition Flag',
                 color_discrete_sequence=px.colors.qualitative.D3)
fig.show()

No relation here.